<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php 
$config = $block->getConfig();
if ($config): 
    // Purchase data
    $purchaseData = $block->purchaseHelper->getPurchaseData();

    // Method code
    $productIsFree = $block->productHelper->isFree($config['product']['id']);
    $methodCode = $productIsFree ? 'free' : $purchaseData['payment_token']['method_code'];

    // UI Logging
    $uiLogging = $config['debug']['debug_enabled'] && $config['debug']['ui_logging_enabled'];

    // Button text
    $buttonText = $block->blockHelper->getButtonText();

    // Display
    $boxId = 'nbn-widget-product-box-' . $config['product']['id'];

    // Product countdown
    $showProductCountdown = $config['products']['show_product_countdown']
    && !empty($config['products']['product_time_from'])
    && !empty($config['products']['product_time_to']);
?>

<!-- Product box -->
<div class="nbn-product-box-container">
    <div id="<?= $block->escapeHtmlAttr($boxId) ?>" class="nbn-product-box">
    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Product parameters -->
        <form id="nbn-product-params-form">
            <?= $block->productHelper->getOptionsHtml($config, $block->getLayout()) ?>      
        </form>

        <!-- Product countdown -->
        <?php if ($showProductCountdown): ?>
        <div class="nbn-product-box-countdown">
            <?= $block->productHelper->getCountdownHtml($config); ?>
        </div>

        <?php endif; ?>
        <!-- Quantity box -->
        <?php if ($config['widgets']['widget_show_product_quantity']): ?>
            <?php /*$block->productHelper->getPriceBoxHtml($config) */ ?>
            <?php /*$block->productHelper->getQuantityBoxHtml($config, $config['product']['quantity_limits']['min']) */ ?>
        <?php endif; ?>

        <!-- Base button -->
        <?= $block->productHelper->getButtonHtml($config) ?>

    </div>
    <div class="nbn-clr"></div> 
</div>
<?php endif; ?>

