<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php 
$config = $block->getConfig();
if ($config): 
    // Purchase data
    $purchaseData = $block->purchaseHelper->getPurchaseData();

    // Method code
    $productIsFree = $block->productHelper->isFree($config['product']['id']);
    $methodCode = $productIsFree ? 'free' : $purchaseData['payment_token']['method_code'];

    // UI Logging
    $uiLogging = $config['debug']['debug_enabled'] && $config['debug']['ui_logging_enabled'];

    // Button text
    $buttonText = $block->blockHelper->getButtonText();

    // Display
    $boxId = 'nbn-widget-product-box-' . $config['product']['id'];

    // Product countdown
    $showProductCountdown = $block->purchaseHelper->isProductTimeValid($config);
?>

<!-- Product box -->
<div class="nbn-product-box-container">
    <div id="<?= $block->escapeHtmlAttr($boxId) ?>" class="nbn-product-box">
    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Form -->
        <form id="nbn-list-form-<?= $config['product']['id'] ?>" name="nbn-list-form-<?= $config['product']['id'] ?>" method="POST" class="nbn-list-form">
            <!-- Base button -->
            <?= $block->productHelper->getButtonHtml($config, $block->getLayout()) ?>

            <!-- Other base fields -->
            <input type="hidden" name="product" value="<?= $config['product']['id'] ?>">
            <input type="hidden" name="selected_configurable_option" value="">
            <input type="hidden" name="related_product" value="">
            <input type="hidden" name="item" value="<?= $config['product']['id'] ?>">

            <!-- Product attributes hidden fields-->
            <?php if (!empty($config['product']['attributes'])): ?>
                <?php foreach ($config['product']['attributes'] as $attribute): ?>
                    <input
                        type="hidden"
                        id="nbn-super-attribute-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($attribute['attribute_id']) ?>"
                        name="super_attribute[<?= $block->escapeHtmlAttr($attribute['attribute_id']) ?>]"
                        value="" 
                    >
                <?php endforeach; ?>
            <?php endif; ?>
        </form>
    </div>
    <div class="nbn-clr"></div> 
</div>
<?php endif; ?>

