<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php 
$config = $block->getConfig();
if ($config): 
    // Purchase data
    $purchaseData = $block->purchaseHelper->getPurchaseData();

    // Method code
    $productIsFree = $block->productHelper->isFree($config['product']['id']);
    $methodCode = $productIsFree ? 'free' : $purchaseData['payment_token']['method_code'];

    // UI Logging
    $uiLogging = $config['debug']['debug_enabled'] && $config['debug']['ui_logging_enabled'];

    // Button text
    $buttonText = $block->blockHelper->getButtonText();

    // Display
    $boxId = 'nbn-widget-product-box-' . $config['product']['id'];

    // Product countdown
    $showProductCountdown = $block->purchaseHelper->isProductTimeValid($config);
?>

            <!-- Base button -->
            <?= $block->productHelper->getButtonHtml($config, $block->getLayout()) ?>
<?php endif; ?>

