<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php 
$config = $block->getConfig();
if ($config): 
    // Purchase data
    $purchaseData = $block->purchaseHelper->getPurchaseData();

    // Method code
    $productIsFree = $block->productHelper->isFree($config['product']['id']);
    $methodCode = $productIsFree ? 'free' : $purchaseData['payment_token']['method_code'];

    // UI Logging
    $uiLogging = $config['debug']['debug_enabled'] && $config['debug']['ui_logging_enabled'];

    // Button text
    $buttonText = $block->blockHelper->getButtonText();
?>

<!-- Product box -->
<div class="nbn-product-box-container">
    <div id="<?= $block->escapeHtmlAttr($boxId) ?>" class="nbn-product-box">
    <!-- Product image -->
    <?php if ($showProductImage): ?>
        <style>
        #<?= $boxId ?> .nbn-product-box-image {
            width: <?= $config['widgets']['widget_image_width'] ?>
        }
        </style>
        <div class="nbn-product-box-image" data-product-id="<?= $config['product']['id'] ?>">
            <img src="<?= $block->escapeUrl($config['product']['images']['medium']) ?>" data-zoom-image="<?= $block->escapeUrl($config['product']['images']['large']) ?>"> 
        </div>
    <?php endif; ?>

    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Product name -->
        <p class="nbn-product-box-name">
            <?= $block->escapeHtml($config['product']['name']) ?>
        </p>

        <!-- Product parameters -->
        <form id="nbn-product-params-form">

            <!-- Todo - Call Product options and attributes templates -->

        </form>
    </div>
    <div class="nbn-clr"></div> 
</div>
<?php endif; ?>

