<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php 
$config = $block->getConfig();
if ($config): 
    // Purchase data
    $purchaseData = $block->purchaseHelper->getPurchaseData();

    // Method code
    $productIsFree = $block->productHelper->isFree($config['product']['id']);
    $methodCode = $productIsFree ? 'free' : $purchaseData['payment_token']['method_code'];

    // UI Logging
    $uiLogging = $config['debug']['debug_enabled'] && $config['debug']['ui_logging_enabled'];

    // Button text
    $buttonText = $block->blockHelper->getButtonText();

    // Display
    $boxId = 'nbn-widget-product-box-' . $config['product']['id'];

    // Product countdown
    $showProductCountdown = $block->purchaseHelper->isProductTimeValid($config);
?>

<!-- Product box -->
<div class="nbn-product-box-container">
    <div id="<?= $block->escapeHtmlAttr($boxId) ?>" class="nbn-product-box">
    <!-- Product image -->
    <?php if ($config['widgets']['widget_show_product_image']): ?>
        <style>
        #<?= $boxId ?> .nbn-product-box-image {
            width: <?= $config['widgets']['widget_image_width'] ?>
        }
        </style>
        <div class="nbn-product-box-image" data-product-id="<?= $config['product']['id'] ?>">
            <img src="<?= $block->escapeUrl($config['product']['images']['medium']) ?>" data-zoom-image="<?= $block->escapeUrl($config['product']['images']['large']) ?>"> 
        </div>
    <?php endif; ?>

    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Product name -->
        <p class="nbn-product-box-name">
            <?= $block->escapeHtml($config['product']['name']) ?>
        </p>

        <!-- Product parameters -->
        <form id="nbn-product-params-form">
            <?= $block->productHelper->getAttributesHtml($config) ?>
            <?= $block->productHelper->getOptionsHtml($config) ?>      
        </form>

        <!-- Product countdown -->
        <?php if ($showProductCountdown): ?>
        <div class="nbn-product-box-countdown">
            <?= $block->productHelper->getCountdownHtml($config); ?>
        </div>
        <?php endif; ?>
        
        <!-- Quantity box -->
        <?php if ($config['widgets']['widget_show_product_quantity']): ?>
            <?= $block->productHelper->getPriceBoxHtml($config) ?>
            <?= $block->productHelper->getQuantityBoxHtml($config, $config['product']['quantity_limits']['min']) ?>
        <?php endif; ?>

        <!-- Base button -->
        <?= $block->productHelper->getButtonHtml($config) ?>

        <!-- Product attributes -->
        <?php if (!empty($config['product']['attributes'])): ?>
            <?php foreach ($config['product']['attributes'] as $attribute): ?>
                <input
                    type="hidden"
                    id="nbn-super-attribute-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($attribute['attribute_id']) ?>"
                    name="nbn[<?= $block->escapeHtmlAttr($config['product']['id']) ?>][super_attribute][<?= $block->escapeHtmlAttr($attribute['attribute_id']) ?>]"
                    value="" 
                >
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
    <div class="nbn-clr"></div> 
</div>
<?php endif; ?>

