<?php 
$agreements = $block->getAgreements();
if (!$agreements) {
    return;
}
?>
<ol id="checkout-agreements" class="agreements checkout items">
    <?php /** @var \Magento\CheckoutAgreements\Api\Data\AgreementInterface $agreement */ ?>
    <?php foreach ($agreements as $agreement): ?>
        <li class="item">
            <form id="checkout-agreements-form-<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>" class="field choice agree required">
                <?php if($agreement->getMode() == \Magento\CheckoutAgreements\Model\AgreementModeOptions::MODE_MANUAL): ?>
                <input type="checkbox"
                       id="agreement-<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>"
                       name="agreement[<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>]"
                       value="1"
                       title="<?= $block->escapeHtml($agreement->getCheckboxText()) ?>"
                       class="checkbox"
                       data-validate="{required:true}"/>
                <label class="label" for="agreement-<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>">
                    <span><?= $agreement->getIsHtml() ? $agreement->getCheckboxText() : $block->escapeHtml($agreement->getCheckboxText()) ?></span>
                    <a href="javascript:void(0)" class="aii-agreement-link" data-role="Agreement" data-id="<?= $agreement->getId() ?>">
                        <?= __('View') ?>
                    </a>
                </label>
                <?php elseif($agreement->getMode() == \Magento\CheckoutAgreements\Model\AgreementModeOptions::MODE_AUTO): ?>
                <div id="checkout-agreements-form-<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>" class="field choice agree">
                    <span><?= $agreement->getIsHtml() ? $agreement->getCheckboxText() : $block->escapeHtml($agreement->getCheckboxText()) ?></span>
                </div>
                <?php endif; ?>
            </form>
        </li>
    <?php endforeach ?>
</ol>