<?php
/** @var \Naxero\AdvancedInstantPurchase\Block\Button $block */
?>

<script>
       console.log('xxx');
       console.log(<?= $block->getConfig() ?>);
</script>

<?php if ($block->isEnabled()) : ?>
<div id="instant-purchase" data-bind="scope:'instant-purchase'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#instant-purchase": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>
        }
    }
</script>
<?php endif; ?>