<?php if ($block->isEnabled()) : ?>
    <?php $uuid = uniqid(); ?>
    <div id="instant-purchase-<?= $uuid ?>" class="aip-button-container" data-bind="scope:'instant-purchase'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
        {
            "#instant-purchase-<?= $uuid ?>": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>
            }
        }
    </script>
<?php endif; ?>