<H1>conf data</H1>
<?php $items = $block->getList(); ?>

<label for="aii-billing-select">
    Click this to highlight the single select element
    <select id="aii-billing-select" class="js-example-basic-single" class="js-states form-control">
        <?php foreach ($items as $item): ?>
            <option value="<?= $item['entity_id'] ?>">
                <?= $item['street'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</label>