<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>
<?php
    // Get the config
    $config = $block->getData('config');
?>
<?php if (!empty($config['product']['attributes'])): ?>
    <?php foreach ($config['product']['attributes'] as $row): ?>                
        <div class="nbn-field">
            <label 
                for="nbn-attribute-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['attribute_id']) ?>"
            >
                <?= $block->escapeHtml($row['label']) ?>
            </label>
            <p>
                <select 
                    id="nbn-attribute-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['attribute_id']) ?>"
                    name="nbn-attribute-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['attribute_id']) ?>"
                    data-product-id="<?= $config['product']['id'] ?>"
                    data-attribute-id="<?= $row['attribute_id'] ?>"
                    data-validate="{'required':true, 'digits': true, 'min':1}"
                >
                    <option value="">test placeholder to remove</option>
                    <?php foreach ($row['values'] as $item): ?>
                        <option value="<?= $block->escapeHtmlAttr($item['value_index']) ?>">
                            <?= $block->escapeHtml($item['label']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <input
                    type="hidden"
                    id="nbn-super-attribute-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['attribute_id']) ?>"
                    name="nbn[<?= $block->escapeHtmlAttr($config['product']['id']) ?>][super_attribute][<?= $block->escapeHtmlAttr($row['attribute_id']) ?>]"
                    value=""
                >
            </p>
        </div>
    <?php endforeach; ?>                
<?php endif; ?>
