<?php 
    // Get the data
    $content = $this->getData('content'); 

    // Display settings
    $showProductImage = $content['popups']['show_product_image'] == 1;
    $showProductName = $content['popups']['show_product_name'] == 1;
    $showProductPrice = $content['popups']['show_product_price'] == 1;
?>

<div class="aip-product-box">
    <?php if ($showProductImage): ?>
        <!-- Product image -->
        <div class="aip-product-box-image">
            <img src="<?= $content['product']['image_url'] ?>"> 
        </div>
    <?php endif; ?>

    <!-- Product info -->
    <div class="aip-product-box-info">
        <!-- Product name -->
        <?php if ($showProductName): ?>
            <p class="aip-product-box-name">
                <?= $content['product']['name'] ?>
            </p>
        <?php endif; ?>

        <!-- Product price -->
        <?php if ($showProductPrice): ?>
            <p class="aip-product-box-price">
                <?= $content['product']['price'] ?>
            </p>
        <?php endif; ?>

        <!-- Product options -->
        <?php if (!empty($content['product']['options'])): ?>
            <?php foreach ($content['product']['options'] as $row): ?>                
                <div class="aip-field">
                    <label for="aip-option-<?= $row['attribute_id'] ?>">
                        <p>
                            <select id="aip-option-<?= $row['attribute_id'] ?>" class="aip-option js-states form-control" data-minimum-results-for-search="Infinity">
                                <option value=""><?= $block->escapeHtml($row['label']) ?></option>
                                <?php foreach ($row['values'] as $item): ?>
                                    <option value="<?= $item['value_index'] ?>">
                                        <?= $item['label'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </p>
                    </label>
                </div>
            <?php endforeach; ?>                
        <?php endif; ?>
    </div>
    <div class="aip-clr"></div>   
</div>