<?php $content = $this->getData('content') ?>
<div class="aip-product-box">
    <div class="aip-product-box-info">
        <p class="aip-product-box-name"><?= $content['product']['name'] ?></p>
        <p class="aip-product-box-price"><?= $content['product']['price'] ?></p>

        <!-- Product options -->
        <?php if (!empty($content['product']['options'])): ?>
            <?php foreach ($content['product']['options'] as $row): ?>                
                <div class="aip-field">
                    <label for="aip-option-<?= $row['attribute_id'] ?>">
                        <span class="aip-label"><?= $block->escapeHtml($row['label']) ?></span>
                        <p>
                            <select id="aip-option-<?= $row['attribute_id'] ?>" class="aip-option aip-select js-states form-control" data-minimum-results-for-search="Infinity">
                                <?php foreach ($row['values'] as $item): ?>
                                    <option value="<?= $item['value_index'] ?>">
                                        <?= $item['label'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </p>
                    </label>
                </div>
            <?php endforeach; ?>                
        <?php endif; ?>
    </div>
    <div class="aip-clr"></div>   
</div>