<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $content = $this->getData('content');

    // Display settings
    $showProductImage = $content['popups']['show_product_image'];
    $showProductName = $content['popups']['show_product_name'];
    $showProductPrice = $content['popups']['show_product_price'];
?>

<div id="nbn-product-box-<?= $content['product']['id'] ?>" class="nbn-product-box">
    <?php if ($showProductImage): ?>
        <!-- Product image -->
        <div class="nbn-product-box-image">
            <img src="<?= $content['product']['image_url'] ?>"> 
        </div>
    <?php endif; ?>

    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Product name -->
        <?php if ($showProductName): ?>
            <p class="nbn-product-box-name">
                <?= $content['product']['name'] ?>
            </p>
        <?php endif; ?>

        <!-- Product price -->
        <?php if ($showProductPrice): ?>
            <p class="nbn-product-box-price">
                <?= $content['product']['price'] ?>
            </p>
        <?php endif; ?>

        <!-- Product options -->
        <?php if (!empty($content['product']['options'])): ?>
            <?php foreach ($content['product']['options'] as $row): ?>                
                <div class="nbn-field">
                    <label for="nbn-option-<?= $content['product']['id'] ?>-<?= $row['attribute_id'] ?>">
                        <p>
                            <select id="nbn-option-<?= $content['product']['id'] ?>-<?= $row['attribute_id'] ?>" data-attribute-id="<?= $row['attribute_id'] ?>" class="nbn-option js-states form-control" data-minimum-results-for-search="Infinity">
                                <option value=""><?= $block->escapeHtml($row['label']) ?></option>
                                <?php foreach ($row['values'] as $item): ?>
                                    <option value="<?= $item['value_index'] ?>">
                                        <?= $item['label'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </p>
                    </label>
                </div>
            <?php endforeach; ?>                
        <?php endif; ?>
    </div>
    <div class="nbn-clr"></div>   
</div>