<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $content = $this->getData('content');
    $isPopup = $this->getData('is_popup');

    // Prepare the box id
    $boxId = $isPopup ? 'nbn-popup-countdown-box-' : 'nbn-widget-countdown-box-';
    $boxId .= $content['product']['id'];
?>

<div id="<?= $boxId ?>" class="nbn-countown-box">
    <div>
        <span class="days"></span>
        <div class="smalltext"><?= __('Days') ?></div>
    </div>
    <div>
        <span class="hours"></span>
        <div class="smalltext"><?= __('Hours') ?></div>
    </div>
    <div>
        <span class="minutes"></span>
        <div class="smalltext"><?= __('Minutes') ?></div>
    </div>
    <div>
        <span class="seconds"></span>
        <div class="smalltext"><?= __('Seconds') ?></div>
    </div>
</div>

<style>
.nbn-countown-box {
  font-family: sans-serif;
  color: #fff;
  display: inline-block;
  font-weight: 100;
  text-align: center;
  font-size: 30px;
}

.nbn-countown-box > div {
  padding: 10px;
  border-radius: 3px;
  background: #00BF96;
  display: inline-block;
}

.nbn-countown-box div > span {
  padding: 15px;
  border-radius: 3px;
  background: #00816A;
  display: inline-block;
}

.nbn-countown-box .smalltext {
  padding-top: 5px;
  font-size: 16px;
}
</style>

<script>
require([
    'jquery',
    'mage/translate',
    'domReady!'
], function($, __) {
    'use strict';

    // Prepare variables
    var boxId = '<?= $boxId ?>';
 
    function getTimeRemaining(endtime) {
        const total = Date.parse(endtime) - Date.parse(new Date());
        const seconds = Math.floor((total / 1000) % 60);
        const minutes = Math.floor((total / 1000 / 60) % 60);
        const hours = Math.floor((total / (1000 * 60 * 60)) % 24);
        const days = Math.floor(total / (1000 * 60 * 60 * 24));
  
        return {
            total,
            days,
            hours,
            minutes,
            seconds
        };
    }   

    function initializeClock(id, endtime) {
        const clock = document.getElementById(id);
        const daysSpan = clock.querySelector('.days');
        const hoursSpan = clock.querySelector('.hours');
        const minutesSpan = clock.querySelector('.minutes');
        const secondsSpan = clock.querySelector('.seconds');

        function updateClock() {
            const t = getTimeRemaining(endtime);
            daysSpan.innerHTML = t.days;
            hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
            minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
            secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);
            if (t.total <= 0) {
                clearInterval(timeinterval);
            }
        }

        updateClock();
        const timeinterval = setInterval(updateClock, 1000);
    }

    const deadline = new Date('<?= $content['buttons']['product_time_limit'] ?>');
    initializeClock(boxId, deadline);
});
</script>