<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $config = $block->getData('config');
    $isPopup = $block->getData('is_popup');

    // Prepare the box id
    $boxId = $isPopup ? 'nbn-popup-countdown-box-' : 'nbn-widget-countdown-box-';
    $boxId .= $config['product']['id'];

    // Prepare the product time limit
    $productTimeTo = $config['products']['product_time_to'];
?>

<div id="<?= $boxId ?>" class="nbn-countown-box">
    <div class="nbn-countdown-digit-box">
        <span class="nbn-days"></span>
        <div class="nbn-smalltext"><?= __('Days') ?></div>
    </div>
    <div class="nbn-countdown-digit-box">
        <span class="nbn-hours"></span>
        <div class="nbn-smalltext"><?= __('Hours') ?></div>
    </div>
    <div class="nbn-countdown-digit-box">
        <span class="nbn-minutes"></span>
        <div class="nbn-smalltext"><?= __('Minutes') ?></div>
    </div>
    <div class="nbn-countdown-digit-box">
        <span class="nbn-seconds"></span>
        <div class="nbn-smalltext"><?= __('Seconds') ?></div>
    </div>
</div>

<script>
require([
    'jquery',
    'mage/translate',
    'domReady!'
], function($, __) {
    'use strict';

    // Prepare variables
    var boxId = '<?= $boxId ?>';
 
    function getTimeRemaining(endtime) {
        const total = Date.parse(endtime) - Date.parse(new Date());
        const seconds = Math.floor((total / 1000) % 60);
        const minutes = Math.floor((total / 1000 / 60) % 60);
        const hours = Math.floor((total / (1000 * 60 * 60)) % 24);
        const days = Math.floor(total / (1000 * 60 * 60 * 24));
  
        return {
            total,
            days,
            hours,
            minutes,
            seconds
        };
    }   

    function initializeClock(id, endtime) {
        const clock = document.getElementById(id);
        const daysSpan = clock.querySelector('.nbn-days');
        const hoursSpan = clock.querySelector('.nbn-hours');
        const minutesSpan = clock.querySelector('.nbn-minutes');
        const secondsSpan = clock.querySelector('.nbn-seconds');

        function updateClock() {
            const t = getTimeRemaining(endtime);
            daysSpan.innerHTML = t.days;
            hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
            minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
            secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);
            if (t.total <= 0) {
                clearInterval(timeinterval);
            }
        }

        updateClock();
        const timeinterval = setInterval(updateClock, 1000);
    }

    const deadline = new Date('<?= $productTimeTo ?>');
    initializeClock(boxId, deadline);
    $('#' + boxId).show();
});
</script>