<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $content = $this->getData('content');
?>

<div class="nbn-gallery-images">
    <?php foreach ($content['product']['images']['gallery'] as $image): ?>
        <div class="nbn-gallery-image">
            <img src="<?= $image['url'] ?>">
        </div>
    <?php endforeach; ?>
</div>