<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the config
    $config = $block->getData('config');
?>
<?php if (!empty($config['product']['options'])): ?>
    <div class="nbn-field nbn-product-options">
        <?= $block->getOptionsHtml($config['product']['id']) ?>
    </div>
<?php endif; ?>