<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $content = $block->getConfig();

    // Display settings
    $showProductImage = $config['popups']['popup_show_product_image'];
    $showProductName = $config['popups']['popup_show_product_name'];
    $showQuantityBox = $config['popups']['popup_show_product_quantity'];
    $boxId = 'nbn-popup-product-box-' . $config['product']['id'];
?>

<div id="<?= $boxId ?>" class="nbn-product-box">
    <?php if ($showProductImage): ?>
        <!-- Product image -->
        <div class="nbn-product-box-image">
            <img src="<?= $block->escapeUrl($config['product']['images']['small']) ?>"> 
        </div>
    <?php endif; ?>

    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Product name -->
        <?php if ($showProductName): ?>
            <p class="nbn-product-box-name">
                <?= $block->escapeHtml($config['product']['name']) ?>
            </p>
        <?php endif; ?>

        <!-- Product options -->
        <?php if (!empty($config['product']['options'])): ?>
            <?php foreach ($config['product']['options'] as $row): ?>                
                <div class="nbn-field">
                    <label for="nbn-option-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['option_id']) ?>">
                        <p>
                            <select id="nbn-option-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['option_id']) ?>" data-product-id="<?= $config['product']['id'] ?>" data-attribute-id="<?= $row['option_id'] ?>" class="nbn-popup-option nbn-option js-states form-control" data-minimum-results-for-search="Infinity">
                                <option data-placeholder="<?= $block->escapeHtml($row['label']) ?>" value=""><?= $block->escapeHtml($row['label']) ?></option>
                                <?php foreach ($row['values'] as $item): ?>
                                    <option value="<?= $block->escapeHtmlAttr($item['value_index']) ?>">
                                        <?= $block->escapeHtml($item['label']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </p>
                    </label>
                </div>
            <?php endforeach; ?>                
        <?php endif; ?>
    </div>
    <div class="nbn-clr"></div>   
</div>

<script>
require([
    'jquery',
    'mage/translate',
    'select2',
    'domReady!'
], function($, __, select2) {
    'use strict';

    // Prepare variables
    var selectOptionSelector = '#<?= $boxId ?>' + ' .nbn-field select';
    var placeholder = $(selectOptionSelector)
    .find('option[data-placeholder="*"]')
    .data('placeholder');

    // Build the product options select lists
    $(selectOptionSelector).select2 ({
        placeholder: placeholder,
        minimumResultsForSearch: -1,
        theme: 'classic'
    });
});
</script>