<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $content = $this->getData('content');

    // Display settings
    $showProductImage = $content['popups']['popup_show_product_image'];
    $showProductName = $content['popups']['popup_show_product_name'];
    $showProductPrice = $content['popups']['popup_show_product_price'];
?>

<div id="nbn-product-box-<?= $block->escapeHtmlAttr($content['product']['id']) ?>" class="nbn-product-box">
    <?php if ($showProductImage): ?>
        <!-- Product image -->
        <div class="nbn-product-box-image">
            <img src="<?= $block->escapeUrl($content['product']['image_url']) ?>"> 
        </div>
    <?php endif; ?>

    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Product name -->
        <?php if ($showProductName): ?>
            <p class="nbn-product-box-name">
                <?= $block->escapeHtml($content['product']['name']) ?>
            </p>
        <?php endif; ?>

        <!-- Product price -->
        <?php if ($showProductPrice): ?>
            <p class="nbn-product-box-price">
                <?= $block->escapeHtml($content['product']['price']) ?>
            </p>
        <?php endif; ?>

        <!-- Product options -->
        <?php if (!empty($content['product']['options'])): ?>
            <?php foreach ($content['product']['options'] as $row): ?>                
                <div class="nbn-field">
                    <label for="nbn-option-<?= $block->escapeHtmlAttr($content['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['option_id']) ?>">
                        <p>
                            <select id="nbn-option-<?= $block->escapeHtmlAttr($content['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['option_id']) ?>" data-product-id="<?= $content['product']['id'] ?>" data-attribute-id="<?= $row['option_id'] ?>" class="nbn-option js-states form-control" data-minimum-results-for-search="Infinity">
                                <option value=""><?= $block->escapeHtml($row['label']) ?></option>
                                <?php foreach ($row['values'] as $item): ?>
                                    <option value="<?= $block->escapeHtmlAttr($item['value_index']) ?>">
                                        <?= $block->escapeHtml($item['label']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </p>
                    </label>
                </div>
            <?php endforeach; ?>                
        <?php endif; ?>
    </div>
    <div class="nbn-clr"></div>   
</div>