<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $config = $block->getData('config');
    $productQuantity = $block->getData('product_quantity');
    $productId = $config['product']['id'];
    $productPrice = $config['product']['price'];
?>

<span id="nbn-product-price-<?= $productId ?>" class="nbn-product-price">
    <?php if ($productQuantity): ?>
        <?= $block->productHelper->renderProductPrice($productId, $productQuantity) ?>
    <?php else: ?>
        <?= $productPrice ?>
    <?php endif; ?>
</span>
