<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $content = $this->getData('content');
    $productQuantity = $this->getData('product_quantity');
    $quantityLimits = $content['product']['quantity_limits'];
    $isPopup = $this->getData('is_popup');
    $productId = $content['product']['id'];

    // Prepare the box id
    $boxId = $isPopup ? 'nbn-popup-qty-box-' : 'nbn-widget-qty-box-';
    $boxId .= $content['product']['id'];
?>

<div id="<?= $boxId ?>" class="nbn-qty-box nbn-qty-buttons-added">
    <span class="nbn-order-total">
        <?= $content['product']['price'] ?>
    </span>
    <input type="button" value="<?= __('-') ?>" class="nbn-qty-minus">
    <input type="number" step="1" min="<?= $quantityLimits['min'] ?>" max="<?= $quantityLimits['max'] ?>" name="nbn_purchase_quantity" value="<?= $productQuantity ?>" title="<?= __('Qty') ?>" class="input-text nbn-qty text">
    <input type="button" value="<?= __('+') ?>" class="nbn-qty-plus">

</div>

<script>
require([
    'jquery',
    'mage/translate',
    'domReady!'
], function($, __) {
    'use strict';

    // Prepare variables
    var boxId = '#<?= $boxId ?>';
    var quantityField = $(boxId + ' .nbn-qty');
    var min = parseInt(quantityField.attr('min'));
    var max = parseInt(quantityField.attr('max'));
    var step = parseInt(quantityField.attr('step'));

    // Update the quantity on page load (popup case)
    updatePrice();

    // Value change event
    quantityField.on('change', function (e) {
        if ($(e.currentTarget).hasClass('nbn-qty')) {
            var currentValue = parseInt($(this).val());
            var condition = currentValue && currentValue !== 'Nan' && currentValue > 0;
            var newValue = condition ? currentValue : min;
            $(this).val(newValue);
            updatePrice();
        }
    });

    // Minus button event
    $(boxId + ' .nbn-qty-minus').off('click touch').on('click touch', function () {
        var quantity = parseInt(quantityField.val());
        var newQuantity = quantity - step;
        var condition = newQuantity && newQuantity !== 'NaN' && newQuantity >= min;
        newQuantity = condition ? newQuantity : min;
        quantityField.val(newQuantity);
        updatePrice();
    });

    // Plus button event
    $(boxId + ' .nbn-qty-plus').off('click touch').on('click touch', function () {
        var quantity = parseInt(quantityField.val());
        var newQuantity = quantity + step;
        var condition = newQuantity && newQuantity !== 'NaN' && newQuantity <= max;

        newQuantity = condition ? newQuantity : max;
        quantityField.val(newQuantity);
        updatePrice();
    });

    // Ajax price update
    function updatePrice() {
        // Ajax price update request
        var updateUrl = '<?= $block->escapeUrl($block->getUrl('naxero-buynow/product/price')); ?>';
        var params = {
            product_id: <?= $productId ?>,
            product_quantity: $(boxId + ' .nbn-qty').val(),
            form_key: window.FORM_KEY
        };
        $.ajax({
                url: updateUrl,
                data: params,
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    $(boxId + ' .nbn-order-total').html(data.html);
                },
                error: function (request, status, error) {
                    console.log(error);
                }
            });
        }
});
</script>