<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $content = $this->getData('content');
    $quantityLimits = $content['product']['quantity_limits'];
    $isPopup = $this->getData('is_popup');

    // Prepare the box id
    $boxId = $isPopup ? 'nbn-popup-qty-box-' : 'nbn-widget-qty-box-';
    $boxId .= $content['product']['id'];
?>

<div id="<?= $boxId ?>" class="nbn-qty-box nbn-qty-buttons-added">
    <input type="button" value="<?= __('-') ?>" class="nbn-qty-minus">
    <input type="number" step="1" min="<?= $quantityLimits['min'] ?>" max="<?= $quantityLimits['max'] ?>" name="nbn_purchase_quantity" value="1" title="<?= __('Qty') ?>" class="input-text nbn-qty text">
    <input type="button" value="<?= __('+') ?>" class="nbn-qty-plus">
</div>

<script>
require([
    'jquery',
    'mage/translate',
    'Naxero_BuyNow/js/view/assets/quantity-box',
    'domReady!'
], function($, __, NbnQtyBox) {
    'use strict';

    // Build the quantity box
    NbnQtyBox.build('<?= $boxId ?>');

});
</script>