<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $content = $this->getData('content');

    // Display settings
    $showProductImage = $content['widgets']['widget_show_product_image'];
    $showProductName = $content['widgets']['widget_show_product_name'];
    $showProductPrice = $content['widgets']['widget_show_product_price'];
    $zoomEnabled = $content['widgets']['widget_zoom_enabled'];
    $isLightbox = $content['widgets']['widget_zoom_type'] == 'lightbox';

    // CSS selectors
    $boxId = 'nbn-product-box-' . $content['product']['id'];
?>

<div id="<?= $block->escapeHtmlAttr($boxId) ?>" class="nbn-product-box">
    <!-- Product image -->
    <?php if ($showProductImage): ?>
        <style>
        #<?= $boxId ?> .nbn-product-box-image {
            width: <?= $content['widgets']['widget_image_width'] ?>
        }
        </style>
        <div class="nbn-product-box-image" data-product-id="<?= $content['product']['id'] ?>">
            <img src="<?= $block->escapeUrl($content['product']['images']['large']) ?>" data-zoom-image="<?= $block->escapeUrl($content['product']['images']['large']) ?>"> 
        </div>
    <?php endif; ?>

    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Product name -->
        <?php if ($showProductName): ?>
            <p class="nbn-product-box-name">
                <?= $block->escapeHtml($content['product']['name']) ?>
            </p>
        <?php endif; ?>

        <!-- Product price -->
        <?php if ($showProductPrice): ?>
            <p class="nbn-product-box-price">
                <?= $block->escapeHtml($content['product']['price']) ?>
            </p>
        <?php endif; ?>

        <!-- Product options -->
        <?php if (!empty($content['product']['options'])): ?>
            <?php foreach ($content['product']['options'] as $row): ?>                
                <div class="nbn-field">
                    <label for="nbn-option-<?= $block->escapeHtmlAttr($content['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['option_id']) ?>">
                        <p>
                            <select id="nbn-option-<?= $block->escapeHtmlAttr($content['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['option_id']) ?>" data-product-id="<?= $content['product']['id'] ?>" data-attribute-id="<?= $row['option_id'] ?>" class="nbn-select nbn-option js-states form-control" data-minimum-results-for-search="Infinity">
                                <option data-placeholder="<?= $block->escapeHtml($row['label']) ?>" value=""><?= $block->escapeHtml($row['label']) ?></option>
                                <?php foreach ($row['values'] as $item): ?>
                                    <option value="<?= $block->escapeHtmlAttr($item['value_index']) ?>">
                                        <?= $block->escapeHtml($item['label']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </p>
                    </label>
                </div>
            <?php endforeach; ?>                
        <?php endif; ?>
    </div>
    <div class="nbn-clr"></div>   
</div>
