<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $config = $block->getData('config');

    // Display settings
    $showProductImage = $config['widgets']['widget_show_product_image'];
    $showProductName = $config['widgets']['widget_show_product_name'];
    $zoomEnabled = $config['widgets']['widget_zoom_enabled'];
    $isLightbox = $config['widgets']['widget_zoom_type'] == 'lightbox';
    $timeLimit = $config['products']['product_time_limit'];

    // Product countdown
    $showProductCountdown = $config['products']['show_product_countdown']
    && !empty($config['products']['product_time_limit']);

    // CSS selectors
    $boxId = 'nbn-widget-product-box-' . $config['product']['id'];
?>

<div id="<?= $block->escapeHtmlAttr($boxId) ?>" class="nbn-product-box">
    <!-- Product image -->
    <?php if ($showProductImage): ?>
        <style>
        #<?= $boxId ?> .nbn-product-box-image {
            width: <?= $config['widgets']['widget_image_width'] ?>
        }
        </style>
        <div class="nbn-product-box-image" data-product-id="<?= $config['product']['id'] ?>">
            <img src="<?= $block->escapeUrl($config['product']['images']['medium']) ?>" data-zoom-image="<?= $block->escapeUrl($config['product']['images']['large']) ?>"> 
        </div>
    <?php endif; ?>

    <!-- Product info -->
    <div class="nbn-product-box-info">
        <!-- Product name -->
        <?php if ($showProductName): ?>
            <p class="nbn-product-box-name">
                <?= $block->escapeHtml($config['product']['name']) ?>
            </p>
        <?php endif; ?>

        <!-- Product countdown -->
        <?php if ($showProductCountdown): ?>
            <div class="nbn-product-box-countdown">
                <?= $block->getData('countdown_html'); ?>
            </div>
        <?php endif; ?>

        <!-- Product options -->
        <?php if (!empty($config['product']['options'])): ?>
            <?php foreach ($config['product']['options'] as $row): ?>                
                <div class="nbn-field">
                    <label for="nbn-option-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['option_id']) ?>">
                        <p>
                            <select id="nbn-option-<?= $block->escapeHtmlAttr($config['product']['id']) ?>-<?= $block->escapeHtmlAttr($row['option_id']) ?>" data-product-id="<?= $config['product']['id'] ?>" data-attribute-id="<?= $row['option_id'] ?>" class="nbn-widget-option nbn-option js-states form-control" data-minimum-results-for-search="Infinity">
                                <option data-placeholder="<?= $block->escapeHtml($row['label']) ?>" value=""><?= $block->escapeHtml($row['label']) ?></option>
                                <?php foreach ($row['values'] as $item): ?>
                                    <option value="<?= $block->escapeHtmlAttr($item['value_index']) ?>">
                                        <?= $block->escapeHtml($item['label']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </p>
                    </label>
                </div>
            <?php endforeach; ?>                
        <?php endif; ?>
    </div>
    <div class="nbn-clr"></div>   
</div>

<script>
require([
    'jquery',
    'mage/translate',
    'select2',
    'domReady!'
], function($, __, select2) {
    'use strict';

    // Prepare variables
    var selectOptionSelector = '#<?= $boxId ?>' + ' .nbn-field select';
    var placeholder = $(selectOptionSelector)
    .find('option[data-placeholder="*"]')
    .data('placeholder');

    // Build the product options select lists
    $(selectOptionSelector).select2 ({
        placeholder: placeholder,
        minimumResultsForSearch: -1,
        theme: 'classic'
    });
});
</script>