<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php $products = $block->getData('products'); ?>
<option value="0"><?= __('Select an option')?></option>
<?php foreach ($products as $product): ?>
    <option value="<?= $product['value'] ?>">
        <?= $product['label'] ?>
    </option>
<?php endforeach; ?>