<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php $products = $block->getData('products'); ?>

<?php foreach ($products as $product): ?>
    <option value="<?= $product['value'] ?>">
        <span class="nbn-float-left" style="float:left; display:inline-block;"><?= $product['label'] ?></span>
        <span class="nbn-float-right" style="float:right; display:inline-block;"><?= $product['id'] ?></span>
        <span class="nbn-clr" style="clear:both; display:inline-block;"></span>
    </option>
<?php endforeach; ?>