<?php 
    // Get the confirmation content
    $content = $this->getData('content');

    // Other payment methods display
    $showOtherPaymentMethods = !empty($content['otherPaymentMethods'])
    && $content['config']['payment_methods']['show_other_allowed'];

    // Product box
    $productBox = $this->getProductBox();

    var_dump($productBox);
?>

<!-- Product box -->
<?= $productBox ?>
 
<!-- Header text -->
<p><?= $content['popup']['header_text'] ?></p>

<!-- Billing address -->
<div class="aip-field">
    <label for="aip-billing-address-select">
        <span class="aip-label"><?= $block->escapeHtml(__('Billing address')) ?></span>
        <p>
            <?php if (!empty($content['addresses'])): ?>
                <select id="aip-billing-address-select" data-field="instant_purchase_billing_address" class="aip-select js-states form-control">
                    <?php foreach ($content['addresses'] as $item): ?>
                        <option value="<?= $item['entity_id'] ?>" <?= $item['entity_id'] == $content['purchase_data']['billing_address']['id'] ? 'selected' : '' ?>>
                            <?= $item['street'] ?>&nbsp;
                            <?= $item['postcode'] ?>&nbsp;
                            <?= $item['city'] ?>&nbsp;
                            <?= $item['country_id'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <span class="aip-plus-icon" data-form="Address"><i class="gg-add"></i></span>
            <?php else: ?>
                <a id="new-billing-address" class="aip-new" data-form="Address" href="javascript:void(0)">
                    <?= __('Create a billing address') ?>
                </a>
            <?php endif; ?>
        </p>
    </label>
</div>

<!-- Shipping address -->
<div class="aip-field">
    <label for="aip-shipping-address-select">
        <span class="aip-label"><?= $block->escapeHtml(__('Shipping address')) ?></span>
        <p>
            <?php if (!empty($content['addresses'])): ?>
                <select id="aip-shipping-address-select" data-field="instant_purchase_shipping_address" class="aip-select js-states form-control">
                    <?php foreach ($content['addresses'] as $item): ?>
                        <option value="<?= $item['entity_id'] ?>" <?= $item['entity_id'] == $content['purchase_data']['shipping_address']['id'] ? 'selected' : '' ?>>
                            <?= $item['street'] ?>&nbsp;
                            <?= $item['postcode'] ?>&nbsp;
                            <?= $item['city'] ?>&nbsp;
                            <?= $item['country_id'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <span class="aip-plus-icon" data-form="Address"><i class="gg-add"></i></span>
            <?php else: ?>
                <a id="new-shipping-address" class="aip-new" data-form="Address" href="javascript:void(0)">
                    <?= __('Create a shipping address') ?>
                </a>
            <?php endif; ?>
        </p>
    </label>
</div>

<!-- Saved cards -->
<?php if (!$content['product']['is_free']): ?>
    <div class="aip-field">
        <label for="aip-payment-method-select">
            <span class="aip-label"><?= $block->escapeHtml(__('Saved cards')) ?></span>
            <p>
                <?php if (!empty($content['savedCards'])): ?>
                    <select id="aip-payment-method-select" data-field="instant_purchase_payment_token" class="aip-select aip-payment-method-select js-states form-control">
                        <?php foreach ($content['savedCards'] as $item): ?>
                            <option value="<?= $item['instance']->getPublicHash() . '*~*' . $item['icon'] ?>">
                                &nbsp;&nbsp;<?= $item['token'] ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <span class="aip-plus-icon" data-form="Card"><i class="gg-add"></i></span>
                <?php else: ?>
                    <a id="new-payment-method" class="aip-new" data-form="Card" href="javascript:void(0)">
                        <?= __('Save a new card') ?>
                    </a>
                <?php endif; ?>
            </p>
        </label> 
    </div>
<?php endif; ?>

<!-- Other payment methods -->
<?php if ($showOtherPaymentMethods && !$content['product']['is_free']): ?>
    <div class="aip-field">
        <label for="aip-other-method-select">
            <input type="checkbox" id="aip-show-other-methods">
            <span class="aip-label"><?= $block->escapeHtml(__('Other payment options')) ?></span>
            <p>
                <select id="aip-other-method-select" data-field="instant_purchase_method_code" class="aip-select aip-other-method-select js-states form-control">
                    <?php foreach ($content['otherPaymentMethods'] as $item): ?>
                        <option value="<?= $item['value'] ?>">
                            &nbsp;&nbsp;<?= $item['label'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </p>
        </label> 
    </div>
<?php endif; ?>

<!-- Shipping method -->
<?php if (!empty($content['addresses']) && !empty($content['savedCards']) && !$content['product']['is_free']): ?>
<div class="aip-field">
    <label for="aip-shipping-method-select">
        <span class="aip-label"><?= $block->escapeHtml(__('Shipping method')) ?></span>
        <p>
            <select id="aip-shipping-method-select" data-field="instant_purchase_shipping" class="aip-select js-states form-control">
                <?php foreach ($content['shippingRates'] as $item): ?>
                    <option value="<?= $item['carrier_code'] ?>">
                        <?= $item['carrier_title'] ?>&nbsp;
                        <?= $item['carrier_price'] ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </p>
    </label>
</div>
<?php endif; ?>

<!-- Footer text -->
<p><?= $content['popup']['footer_text'] ?></p>

