<?php if ($block->isEnabled()) : ?>
    <?php $pid = $block->getProduct()->getId() ?>
    <div id="aip-<?= $pid ?>" class="aip-button-container" data-bind="scope:'instant-purchase'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
        {
            "#instant-purchase-<?= $pid ?>": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>
            }
        }
    </script>
<?php endif; ?>