<?php
/** @var \Naxero\AdvancedInstantPurchase\Block\Button\ViewButton $block */
?>

<?php if ($block->isEnabled()) : ?>
<div id="instant-purchase" class="aip-button-container" data-bind="scope:'instant-purchase'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#instant-purchase": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>
        }
    }
</script>
<?php endif; ?>