<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the confirmation content
    $data = $block->getData('data');

    // Get the confirmation request parameters
    $params = $block->getData('params');

    $productQantity = $block->getData('product_quantity');
    $productId = $data['config']['product']['id'];
?>

<!-- Form-->
<form 
    id="nbn-order-form-<?= $productId ?>"
    name="nbn-order-form-<?= $productId ?>"
    method="POST"
    class="nbn-order-form"
>
    <!-- Header text -->
    <p><?= $block->escapeHtml($data['popup']['header_text'])?></p>

    <!-- Product info -->
    <input type="hidden" name="nbn[params][product_id]" value="<?= $productId ?>">
    <input type="hidden" name="nbn[params][qty]" value="<?= $productQantity ?>">

    <!-- Shipping method -->
    <?php if (!empty($data['addresses']) && !empty($data['savedCards']) && !$data['product']['is_free']): ?>
    <div class="nbn-fields">
        <div class="nbn-field">
            <label for="nbn-shipping-method-id">
                <span class="nbn-label"><?= $block->escapeHtml(__('Shipping method')) ?></span>
                <p>
                    <select
                        id="nbn-shipping-method-id"
                        name="nbn[params][shipping_method_id]"
                        data-field="shipping_method_code"
                        class="nbn-select js-states form-control"
                    >
                        <?php foreach ($data['shippingRates'] as $item): ?>
                            <option value="<?= json_encode($item) ?>">
                                <?= $block->escapeHtml($item['carrier_title']) ?>&nbsp;
                                <?= $block->toolsHelper->renderAmount($item['carrier_price'], true, false) ?>
                            </option>       
                        <?php endforeach; ?>
                    </select>
                    <input
                        type="hidden"
                        name="nbn[params][shipping_carrier_code]"
                        value="<?= $data['shippingRates'][0]['carrier_code'] ?>"
                    >
                    <input
                        type="hidden"
                        name="nbn[params][shipping_method_code]"
                        value="<?= $data['shippingRates'][0]['method_code'] ?>"
                    >
                </p>
            </label>
        </div>
    </div>
    <?php endif; ?>

    <!-- Shipping address -->
    <div class="nbn-field">
        <label for="nbn-shipping-address-id">
            <span class="nbn-label">
                <?= $block->escapeHtml(__('Shipping address')) ?>
            </span>
            &nbsp;|&nbsp;
            <a id="new-shipping-address" class="nbn-new-address nbn-address-link" href="<?= $block->getUrl('customer/address/new')?>">
                <?= $block->escapeHtml(__('New')) ?>
            </a>
            <p>
                <?php if (!empty($data['addresses'])): ?>
                    <select
                        id="nbn-shipping-address-id"
                        name="nbn[params][shipping_address_id]"
                        data-field="shipping_address"
                        class="nbn-select js-states form-control"
                    >
                        <?php foreach ($data['addresses'] as $item): ?>
                            <option value="<?= $block->escapeHtmlAttr($item['entity_id']) ?>" <?= $item['entity_id'] == $data['purchase_data']['shipping_address']['id'] ? 'selected' : '' ?>>
                                <?= $block->escapeHtml($item['street']) ?>&nbsp;
                                <?= $block->escapeHtml($item['postcode']) ?>&nbsp;
                                <?= $block->escapeHtml($item['city']) ?>&nbsp;
                                <?= $block->escapeHtml($item['country_id']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php else: ?>
                    <p><i><?= $block->escapeHtml(__('No records available.')) ?></i></p>
                <?php endif; ?>
            </p>
        </label>
    </div>

    <!-- Billing address -->
    <div class="nbn-field">
        <label for="nbn-billing-address-id">
            <span class="nbn-label">
                <?= $block->escapeHtml(__('Billing address')) ?>
            </span>
            &nbsp;|&nbsp;
            <a id="new-billing-address" class="nbn-new-address nbn-address-link" href="<?= $block->getUrl('customer/address/new')?>">
                <?= $block->escapeHtml(__('New')) ?>
            </a>
            <p>
                <?php if (!empty($data['addresses'])): ?>
                    <select
                        id="nbn-billing-address-id"
                        name="nbn[params][billing_address_id]"
                        data-field="billing_address"
                        class="nbn-select js-states form-control"
                    >
                        <?php foreach ($data['addresses'] as $item): ?>
                            <option value="<?= $block->escapeHtmlAttr($item['entity_id']) ?>" <?= $item['entity_id'] == $data['purchase_data']['billing_address']['id'] ? 'selected' : '' ?>>
                                <?= $block->escapeHtml($item['street']) ?>&nbsp;
                                <?= $block->escapeHtml($item['postcode']) ?>&nbsp;
                                <?= $block->escapeHtml($item['city']) ?>&nbsp;
                                <?= $block->escapeHtml($item['country_id']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php else: ?>
                    <p><i><?= $block->escapeHtml(__('No records available.')) ?></i></p>
                <?php endif; ?>
            </p>
        </label>
    </div>

    <!-- Saved cards -->
    <?php if (!$data['product']['is_free']): ?>
        <div class="nbn-field">
            <label for="nbn-payment-method-code">
                <span class="nbn-label">
                    <?= $block->escapeHtml(__('Saved cards')) ?>
                </span>
                <p>
                    <?php if (!empty($data['savedCards'])): ?>
                        <select
                            id="nbn-payment-method-code"
                            name="nbn[params][payment_method_code]"
                            data-field="payment_token"
                            class="nbn-select nbn-payment-method-code js-states form-control"
                        >
                            <?php foreach ($data['savedCards'] as $item): ?>
                                <option
                                    value="<?= $item['instance']->getPublicHash() ?>"
                                    data-icon-url="<?= $item['icon'] ?>"
                                >
                                    &nbsp;&nbsp;<?= $item['token'] ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    <?php else: ?>
                        <p><i><?= $block->escapeHtml(__('No records available.')) ?></i></p>
                    <?php endif; ?>
                </p>
            </label> 
        </div>
    <?php endif; ?>
</form>

<!-- Footer text -->
<p><?= $block->escapeHtml($data['popup']['footer_text']) ?></p>