<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $config = $block->getData('config');
?>

<div class="nbn-coupon-box">
    <input id="nbn-coupon-code" type="text" name="nbn-coupon-code" value="" placeholder="<?= __('Discount code') ?>" class="input-text">
    <button class="action primary instant-purchase nbn-button">
        <?= __('Apply') ?>
    </button>
</div>