<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $config = $block->getData('config');
    $productQantity = $block->getData('product_quantity');
?>

<div class="nbn-summary-box">
<table>
  <thead>
    <tr>
      <th><?= __('Reference') ?></th>
      <th><?= __('Name') ?></th>
      <th><?= __('Quantity') ?></th>
      <th><?= __('Price') ?></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><?= $config['product']['sku'] ?></td>
      <td><?= $config['product']['name'] ?></td>
      <td><?= $block->getQuantityBoxHtml($config, $productQantity) ?></td>
      <td><?= $block->getPriceBoxHtml($config) ?></td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
    <td>&nbsp;</td>
      <td>&nbsp;</td>
     <td>Shipping</td>
      <td>$180</td>
    </tr>
    <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
      <td>Total</td>
      <td>$180</td>
    </tr>
  </tfoot>
</table>
</div>

<script>
require([
    'jquery',
    'mage/translate',
    'domReady!'
], function($, __) {
    'use strict';

    

});
</script>