<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
    // Get the data
    $config = $block->getData('config');
?>

<div id="<?= $boxId ?>" class="nbn-summary-box">
 <h1> order summary</h1>
</div>

<script>
require([
    'jquery',
    'mage/translate',
    'domReady!'
], function($, __) {
    'use strict';

    

});
</script>