<if args="showButton() || <?= json_encode($block->getConfig()['guest/show_guest_button']) ?>">
    <button type="button"
           class="action primary instant-purchase"
           data-bind="click: isLoggedIn() ? purchasePopup : loginPopup, css: isLoggedIn() ? 'aii-login-popup' : ''"
           attr="title: $t(buttonText)">
           <span translate="buttonText" />
    </button>
    <input if="paymentToken()"
           type="hidden"
           name="instant_purchase_payment_token"
           ko-value="paymentToken().publicHash" />
    <input if="shippingAddress()"
           type="hidden"
           name="instant_purchase_shipping_address"
           ko-value="shippingAddress().id" />
    <input if="billingAddress()"
           type="hidden"
           name="instant_purchase_billing_address"
           ko-value="billingAddress().id" />
    <if args="shippingMethod()">
        <input type="hidden"
               name="instant_purchase_carrier"
               ko-value="shippingMethod().carrier" />
        <input type="hidden"
               name="instant_purchase_shipping"
               ko-value="shippingMethod().method" />
    </if>
</if>
