<!-- ko if: (showButton() || bypassLogin()) -->
    <button type="button"
           class="action primary instant-purchase aip-button"
           data-bind="afterRender: shouldDisableButton, css: isLoggedIn() ? 'aip-login-popup' : ''"
           attr="id: getButtonId(), title: $t(buttonText)">
           <span translate="buttonText" />
    </button>
    <input if="paymentToken()"
           type="hidden"
           name="instant_purchase_payment_token"
           ko-value="paymentToken().publicHash" />
    <input if="shippingAddress()"
           type="hidden"
           name="instant_purchase_shipping_address"
           ko-value="shippingAddress().id" />
    <input if="billingAddress()"
           type="hidden"
           name="instant_purchase_billing_address"
           ko-value="billingAddress().id" />
    <if args="shippingMethod()">
        <input type="hidden"
               name="instant_purchase_carrier"
               ko-value="shippingMethod().carrier" />
        <input type="hidden"
               name="instant_purchase_shipping"
               ko-value="shippingMethod().method" />
    </if>
<!-- /ko -->