<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$element = $block->getData('element');
?>

<div class="field">
    <label><?= __('Date') ?></label>
    <input type="text" class="input-text" id="<?= $element->getId() ?>" name="<?= $element->getName() ?>" />
</div>

<script>
require([
    'jquery',
    'mage/translate',
    'mage/calendar'
], function ($, __, calendar) {
    $('#<?= $element->getId() ?>').calendar({
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        currentText: __('Go Today'),
        closeText: __('Close'),
        showWeek: true
    });
});
</script>
