<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$element = $block->getData('element');
$categories = $block->getData('categories');
?>

<!-- Select 2 CSS -->
<!-- Todo - Move to local -->
<style>
    @import url('https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css');

    .admin__field .control-value {
        display: none;
    }

    .nbn-category-select-level-0 {
        padding-left: 0em;
        font-weight: bold;
    }

    .nbn-category-select-level-1 {
        padding-left: 1em;
    }

    .nbn-category-select-level-2 {
        padding-left: 2em;
    }

    .nbn-category-select-level-3 {
        padding-left: 3em;
    }

    .nbn-category-select-level-4 {
        padding-left: 4em;
}
</style>

<!-- Category list selector -->
<div>
    <label class="label admin__field-label" for="<?= $element->getId() ?>">
        <span><?= __('Select a category') ?></span>
    </label>
    <select id="<?= $element->getId() ?>" name="<?= $element->getName() ?>">
    <?php foreach ($categories as $category): ?>
        <option class="nbn-category-select-level-<?= $category['level'] ?>" value="<?= $category['id'] ?>" <?= $category['id'] == $element->getValue() ? 'selected' : '' ?>>
            <?php
                for ($i = 0; $i < (int) $category['level']; $i++) {
                    if ($i >= 0) echo '-';
                }
            ?>
            <?= $category['name'] ?>
        </option>
    <?php endforeach; ?>
    </select>
</div>

<!-- Select 2 script -->
<script>
    require([
        'jquery',
        'mage/translate',
        'select2',
        'domReady!'
], function($, __, select2) {
    'use strict';

    // Category selector select
    $('<?= $element->getId() ?>').select2({
        placeholder: __('Filter by category'),
        theme: 'classic',
        templateResult: function (data) { 
            // Hierarchical display for sub categories
            if (!data.element) {
                return data.text;
            }
            var $element = $(data.element);
            var $wrapper = $('<span></span>');
            $wrapper.addClass($element[0].className);
            $wrapper.text(data.text);

            return $wrapper;
        }
    });    

    // Category selector change event
    $('<?= $element->getId() ?>').on('change', function() {
        // Prepare the parameters
        var updateUrl = '<?= $block->escapeUrl($block->getUrl('naxero-buynow/widget/form')); ?>';
        var data = {
            category_id: $(this).val(),
            form_key: window.FORM_KEY
        };

        // Ajax request
        $.ajax({
            url: updateUrl,
            data: data,
            type: 'post',
            dataType: 'json',
            success: function (data) {
                $('#<?= $element->getId() ?>').empty().html(data.html);
            },
            error: function (request, status, error) {
                console.log(error);
            }
        });
    });
});
</script>