<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$element = $block->getData('element');
$categories = $block->getData('categories');

// Todo - Move css styles below to admin css file
?>

<!-- Select 2 CSS -->
<style>
    .admin__field .control-value {
        display: none;
    }

    .nbn-category-select-level-0 {
        padding-left: 0em;
        font-weight: bold;
    }

    .nbn-category-select-level-1 {
        padding-left: 1em;
    }

    .nbn-category-select-level-2 {
        padding-left: 2em;
    }

    .nbn-category-select-level-3 {
        padding-left: 3em;
    }

    .nbn-category-select-level-4 {
        padding-left: 4em;
}
</style>

<!-- Category selector -->
<div>
    <select id="<?= $element->getId() ?>" name="<?= $element->getName() ?>">
    <?php foreach ($categories as $category): ?>
        <option class="nbn-category-select-level-<?= $category['level'] ?>" value="<?= $category['id'] ?>" <?= $category['id'] == $element->getValue() ? 'selected' : '' ?>>
            <?php
            for ($i = 0; $i < (int) $category['level']; $i++) {
                if ($i >= 0) { echo '-';
                }
            }
            ?>
            <?= $category['name'] ?>
        </option>
    <?php endforeach; ?>
    </select>
    <input type="hidden" id="nbn-category-selector" name="nbn-category-selector" value="<?= $element->getId() ?>">
</div>