<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$element = $block->getData('element');
?>

<div class="field">
    <input type="text" id="nbn-calendar-field" value="<?= $element->getValue() ?>">
    <input type="hidden" id="<?= $element->getId() ?>" name="<?= $element->getName() ?>" value="<?= $element->getValue() ?>">
</div>

<script>
require([
    'jquery',
    'mage/translate',
    'mage/calendar'
], function ($, __, calendar) {
    $('#nbn-calendar-field').calendar({
        changeMonth: true,
        changeYear: true,
        showButtonPanel: false,
        showWeek: false
    });

    $('#nbn-calendar-field').on('change', function() {
        $('#<?= $element->getId() ?>').val($(this).val());
    });
});
</script>
