<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$element = $block->getData('element');
?>

<!-- Select 2 CSS -->
<!-- Product list selector -->
<div>
    <select id="<?= $element->getId() ?>" name="<?= $element->getName() ?>">
        <option value="random"><?= _('Random') ?></option>
        <option value="latest"><?= _('Latest') ?></option>
        <option value="oldest"><?= _('Oldest') ?></option>
        <option value="highest_price"><?= _('Highest price') ?></option>
        <option value="lowest_price"><?= _('Lowest price') ?></option>
    </select>
</div>

<!-- Select 2 script -->
<script>
    require([
        'jquery',
        'mage/translate',
        'select2',
        'domReady!'
], function($, __, select2) {
    'use strict';

    // Product selector
    $('#<?= $element->getId() ?>').select2({
        placeholder: __('Select an option'),
        theme: 'classic'
    });
});
</script>