<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$element = $block->getData('element');
$products = $block->getData('products');
?>

<!-- Select 2 CSS -->
<!-- Todo - Move to local -->
<style>
    @import url('https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css');
</style>

<!-- Product list selector -->
<div>
    <select id="nbn-product-selector">
    <?php foreach ($products as $product): ?>
        <option value="<?= $product['value'] ?>" <?= $product['value'] == $element->getValue() ? 'selected' : '' ?>>
            <?= $product['label'] ?>
        </option>
    <?php endforeach; ?>
    </select>
    <input type="hidden" id="<?= $element->getId() ?>" name="<?= $element->getName() ?>" value="">
</div>

<!-- Select 2 script -->
<script>
    require([
        'jquery',
        'mage/translate',
        'select2',
        'domReady!'
], function($, __, select2) {
    'use strict';

    // Product selector
    $('#nbn-product-selector').select2({
        placeholder: __('Select an option'),
        theme: 'classic'
    });

    // Field event
    $('#nbn-product-selector').on('change', function() {
        $('#<?= $element->getId() ?>').val($(this).val());
    });
});
</script>