<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$element = $block->getData('element');
$options = $block->getData('options');

?>

<!-- Product list selector -->
<div>
    <select id="<?= $element->getId() ?>" name="<?= $element->getName() ?>">
        <?php foreach ($options as $option): ?>
            <option value="<?= $option['value'] ?>" <?= $element->getValue() == $option['value'] ? 'selected' : '' ?>>
                <?= $option['label'] ?>
            </option>
        <?php endforeach; ?>
    </select>
    <input type="hidden" id="nbn-product-filter-selector" name="nbn-product-filter-selector" value="<?= $element->getId() ?>">
</div>

<!-- Select 2 script -->
<script>
    require([
        'jquery',
        'mage/translate',
        'select2',
        'domReady!'
], function($, __, select2) {
    'use strict';

    // Product selector
    $('#<?= $element->getId() ?>').select2({
        placeholder: __('Select an option'),
        minimumResultsForSearch: -1,
        theme: 'classic'
    });
});
</script>