<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$elementId = $block->getData('element_id');
$elementLabel = $block->getData('element_label');
$elementName = $block->getData('element_name');
$elementValue = $block->getData('element_value');
$products = $block->getData('product_list');
?>

<!-- Select 2 CSS -->
<!-- Todo - Move to local -->
<style>
 @import url('https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css');

 .admin__field .control-value {
     display: none;
 }
</style>

<!-- Product list selector -->
<div class="nbn-product-selector">
    <label class="label admin__field-label" for="<?= $elementId ?>">
        <span><?= $elementLabel ?></span>
    </label>
    <select id="<?= $elementId ?>" name="<?= $elementName ?>">
    <?php foreach ($products as $product): ?>
        <option value="<?= $product['value'] ?>" <?= $product['value'] == $elementValue ? 'selected' : '' ?>>
            <?= $product['label'] ?>
        </option>
    <?php endforeach; ?>
    </select>
</div>

<!-- Select 2 script -->
<script>
    require([
        'jquery',
        'select2'
], function($, select2) {
    'use strict';

    $('#<?= $elementId ?>').select2({
        theme: 'classic'
    });
});
</script>