<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php
// Get the block data
$element = $block->getData('element');
?>

<!-- Product selection mode selector -->
<div>
    <select id="nbn-product-selection-mode" data-target-id="<?= $element->getId() ?>">
        <option value="category"><?= _('Category') ?></option>
        <option value="product"><?= _('Product') ?></option>
    </select>
    <input type="hidden" id="<?= $element->getId() ?>" name="<?= $element->getName() ?>" value="">
</div>

<!-- Select 2 script -->
<script>
    require([
        'jquery',
        'mage/translate',
        'select2',
        'domReady!'
], function($, __, select2) {
    'use strict';

    // Product selection mode
    $('#nbn-product-selection-mode').select2({
        placeholder: __('Select an option'),
        minimumResultsForSearch: -1,
        theme: 'classic'
    });

    // Field event
    $('#nbn-product-selection-mode').on('change', function() {
        $('#<?= $element->getId() ?>').val($(this).val());
    });

});
</script>