<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<style>
    @import url('https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css');
</style>

<script>
    require([
        'jquery',
        'mage/translate',
        'domReady!'
], function($, __) {
    'use strict';

    // Product selection mode event
    $('#nbn-product-selection-mode').on('change', function() {
        // Update the hidden field
        $('#' + $(this).data('target-id')).val($(this).val());

        // Toggle the dependent fields
        if ($(this).val() == 'product') {
            $('#nbn-product-selector').parent('.admin__field').show();
            $('#nbn-product-filter-selector').parent('.admin__field').hide();
        }
        else if ($(this).val() == 'category') {
            $('#nbn-product-selector').parent('.admin__field').hide();
            $('#nbn-product-filter-selector').parent('.admin__field').show();
        }
    });

    // Category selector change event
    $('#nbn-category-selector').on('change', function() {
        // Update the hidden field
        $('#' + $(this).data('target-id')).val($(this).val());

        // Prepare the parameters
        var updateUrl = '<?= $block->escapeUrl($block->getUrl('naxero-buynow/widget/form')); ?>';
        var data = {
            category_id: $(this).val(),
            form_key: window.FORM_KEY
        };

        // Ajax request
        $.ajax({
            url: updateUrl,
            data: data,
            type: 'post',
            dataType: 'json',
            success: function (data) {
                $('#nbn-product-selector').empty().html(data.html);
            },
            error: function (request, status, error) {
                console.log(error);
            }
        });
    });





});
</script>