<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<!-- Widget form scripts -->
<script>
require([
    'jquery',
    'mage/translate',
    'select2',
    'domReady!'
], function($, __, select2) {
    'use strict';

    // Selectors
    var categorySelector = $('#' + $('#nbn-category-selector').val());
    var productSelector = $('#' + $('#nbn-product-selector').val());

    // Category selector select
    categorySelector.select2({
        placeholder: __('Filter by category'),
        theme: 'classic',
        templateResult: function (data) { 
            // Hierarchical display for sub categories
            if (!data.element) {
                return data.text;
            }
            var $element = $(data.element);
            var $wrapper = $('<span></span>');
            $wrapper.addClass($element[0].className);
            $wrapper.text(data.text);

            return $wrapper;
        }
    });    

    // Category selector change event
    categorySelector.on('change', function() {
        // Prepare the parameters
        var updateUrl = '<?= $block->escapeUrl($block->getUrl('naxero-buynow/widget/form')); ?>';
        var data = {
            category_id: $(this).val(),
            form_key: window.FORM_KEY
        };

        // Ajax request
        $.ajax({
            url: updateUrl,
            data: data,
            type: 'post',
            dataType: 'json',
            success: function (data) {
                var selectorId = productSelector.val();
                $(selectorId).empty().html(data.html);
            },
            error: function (request, status, error) {
                console.log(error);
            }
        });
    });

    // Product selector
    productSelector.select2({
        placeholder: __('Select an option'),
        theme: 'classic'
    });

    // Product filter selector
    var productFilterSelector = $('#' + $('#nbn-product-filter-selector').val());
    productFilterSelector.select2({
        placeholder: __('Select an option'),
        minimumResultsForSearch: -1,
        theme: 'classic'
    });

    // Product selection mode
    var productSelectionMode = $('#' + $('#nbn-product-selection-mode').val());
    productSelectionMode.select2({
        placeholder: __('Select an option'),
        minimumResultsForSearch: -1,
        theme: 'classic'
    });

    // Product selection mode event
    $('#<?= $element->getId() ?>').on('change', function() {
        // Prepare the variables
        var productSelector = $('#' + $('#nbn-product-selector').val());
        var productFilterSelector = $('#' + $('#nbn-product-filter-selector').val());

        // Toggle the dependent fields
        if ($(this).val() == 'product') {
            productSelector.closest('.admin__field.field').show();
            productFilterSelector.closest('.admin__field.field').hide();
        }
        else if ($(this).val() == 'category') {
            productSelector.closest('.admin__field.field').hide();
            productFilterSelector.closest('.admin__field.field').show();
        }
    });
});
</script>