<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<script>
require([
    'jquery',
    'mage/translate',
    'select2',
    'domReady!'
], function($, __, select2) {
    'use strict';

    // Selectors
    var categorySelector = $('#' + $('#nbn-category-selector').val());
    var productSelector = $('select[name="parameters[product_id]"]');

    // Category selector select
    categorySelector.select2({
        placeholder: __('Filter by category'),
        theme: 'classic',
        templateResult: function (data) { 
            // Hierarchical display for sub categories
            if (!data.element) {
                return data.text;
            }
            var $element = $(data.element);
            var $wrapper = $('<span></span>');
            $wrapper.addClass($element[0].className);
            $wrapper.text(data.text);

            return $wrapper;
        }
    });    

    // Category selector change event
    categorySelector.on('change', updateProductSelector);

    // Product selector select
    productSelector.select2({
        placeholder: __('Select an option'),
        theme: 'classic'
    });

    // Product selector default values
    var selectedCategoryId = parseInt(categorySelector.val());
    var selectedProductId = parseInt(productSelector.val());
    if (selectedProductId > 0) {
        updateProductSelector(selectedProductId);
    }

    // Functions
    function updateProductSelector(selectedProductId) {
        // Default argument value
        selectedProductId = selectedProductId || null;

        // Prepare the parameters
        // Todo - Get "naxero-buynow" url prefix from config, not hard coded. Also check all remaining hard coded in code base
        var updateUrl = '<?= $block->escapeUrl($block->getUrl('naxero-buynow/widget/form')); ?>';
        var params = {
            category_id: categorySelector.val(),
            form_key: window.FORM_KEY
        };

        // Ajax request
        $.ajax({
            url: updateUrl,
            data: params,
            type: 'post',
            dataType: 'json',
            success: function (data) {
                productSelector.empty().html(data.html);
                if (selectedProductId) {
                    productSelector.val(selectedProductId)
                }

            },
            error: function (request, status, error) {
                console.log(error);
            }
        });
    }
});
</script>