<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */

?>
<?php
    // Get the config
    $config = $block->getData('config');
    $productIsFree = $block->getData('isFree');

    // Process the block display logic
    $purchaseData = $block->purchaseHelper->getPurchaseData();
    $methodCode = $productIsFree ? 'free' : $purchaseData['payment_token']['method_code'];
    $formKey = $config['product']['form_key'];
    $uiLogging = $config['debug']['debug_enabled'] && $config['debug']['ui_logging_enabled'];
    $buttonText = $block->blockHelper->getButtonText();
?>

<!-- Purchase button -->
<div id="nbn-<?= $block->escapeHtmlAttr($config['product']['id']) ?>" class="nbn-button-container">    
    <button 
        id="<?= $block->escapeHtmlAttr($config['product']['button_id']) ?>"
        data-product-id="<?= $block->escapeHtmlAttr($config['product']['id']) ?>"
        type="button"
        disabled="disabled"
        class="<?= $block->escapeHtmlAttr($block->purchaseHelper->getButtonCss()) ?> action primary instant-purchase nbn-button"
        title="<?= $block->escapeHtmlAttr(__($buttonText)) ?>">
        <?= $block->escapeHtml(__($buttonText)) ?>
    
        <?php if ($uiLogging): ?>
            <div id="nbn-ui-logger-button-<?= $block->escapeHtmlAttr($config['product']['id']) ?>" class="nbn-ui-logger-button">
                <a href="javascript:void(0)" title="<?= $block->escapeHtmlAttr(__('View logs')) ?>">&#9432;</a>
            </div>
        <?php endif; ?> 
    </button>

    <!-- Form -->
    <form name="nbn-list-form" method="post" class="nbn-list-form">
        <input type="hidden" name="nbn[<?= $block->escapeHtmlAttr($config['product']['id']) ?>][instant_purchase_payment_token]" value="<?= $purchaseData['payment_token']['public_hash'] ?>" />
        <input type="hidden" name="nbn[<?= $block->escapeHtmlAttr($config['product']['id']) ?>][instant_purchase_method_code]" value="<?= $methodCode ?>" />
        <input type="hidden" name="nbn[<?= $block->escapeHtmlAttr($config['product']['id']) ?>][instant_purchase_shipping_address]" value="<?= $purchaseData['shipping_address']['id'] ?>" />
        <input type="hidden" name="nbn[<?= $block->escapeHtmlAttr($config['product']['id']) ?>][instant_purchase_billing_address]" value="<?= $purchaseData['billing_address']['id'] ?>" />
        <input type="hidden" name="nbn[<?= $block->escapeHtmlAttr($config['product']['id']) ?>][instant_purchase_carrier]" value="<?= $purchaseData['shipping_method']['carrier'] ?>" />
        <input type="hidden" name="nbn[<?= $block->escapeHtmlAttr($config['product']['id']) ?>][instant_purchase_shipping]" value="<?= $purchaseData['shipping_method']['method'] ?>" />
        <input id="nbn-form-key-<?= $block->escapeHtmlAttr($config['product']['id']) ?>" type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($formKey) ?>">
    </form>

    <script type="text/x-magento-init">
        {
            "*": {
                "Naxero_BuyNow/js/view/handler": <?= json_encode(['config' => $config], true) ?>
            }
        }
    </script>
</div>
