<?php $config = $block->getConfig(); ?>
<?php if ($config && $block->purchaseHelper->canDisplayButton()): ?>
<?php
    $pid = $block->getData('product_id');
    //var_dump($pid);

    $product = $block->getProduct($pid);
    $productId = $product->getId();
    if ($this->configHelper->bypassOos($productId)) {
        // Display parameters
        $purchaseData = $block->purchaseHelper->getPurchaseData();
        $buttonId = 'aip-button-' . $productId;
        $productIsFree = $block->productHelper->isFree($product);
        $methodCode = $productIsFree ? 'free' : $purchaseData['paymentToken']['method_code'];
        $isListView = $block->productHelper->isListView();
        $formKey = $block->productHelper->getFormKey();

        // JS component config
        $jsConfig = [
            'jsConfig' => array_merge(
                $this->customerHelper->getUserParams(),
                [
                    'product' => [
                        'id' => $this->getProduct()->getId(),
                        'formKey' => $formKey,
                        'buttonSelector' => '#' . $buttonId
                    ],
                ]
            )
        ];
    }
?>
<div id="aip-<?= $productId ?>" class="aip-button-container">
    <button 
        id="<?= $buttonId ?>"
        type="button"
        disabled="disabled"
        class="<?= $block->purchaseHelper->getButtonCss() ?> action primary instant-purchase aip-button"
        title="<?= __($config['general']['button_text']) ?>">
        <?= __($config['general']['button_text']) ?>
    </button>
    <?php if ($isListView): ?>
        <form name="aip-list-form" method="post" class="aip-list-form">
    <?php endif; ?>
        <input type="hidden" name="aip[<?= $productId ?>][instant_purchase_payment_token]" value="<?= $purchaseData['paymentToken']['publicHash'] ?>" />
        <input type="hidden" name="aip[<?= $productId ?>][instant_purchase_method_code]" value="<?= $methodCode ?>" />
        <input type="hidden" name="aip[<?= $productId ?>][instant_purchase_shipping_address]" value="<?= $purchaseData['shippingAddress']['id'] ?>" />
        <input type="hidden" name="aip[<?= $productId ?>][instant_purchase_billing_address]" value="<?= $purchaseData['billingAddress']['id'] ?>" />
        <input type="hidden" name="aip[<?= $productId ?>][instant_purchase_carrier]" value="<?= $purchaseData['shippingMethod']['carrier'] ?>" />
        <input type="hidden" name="aip[<?= $productId ?>][instant_purchase_shipping]" value="<?= $purchaseData['shippingMethod']['method'] ?>" />
        <input type="hidden" name="form_key" value="<?= $formKey ?>" />
    <?php if ($isListView): ?>
        </form>
    <?php endif; ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "aip": <?= json_encode($jsConfig); ?>
            }
        }
    </script>
</div>
<?php endif; ?> 