<?php
    $config = $block->getConfig();
    if ($config && $block->purchaseHelper->canDisplayButton()) {
        // Display parameters
        $purchaseData = $block->purchaseHelper->getPurchaseData();
        $product = $block->getProduct();
        $productId = $product->getId();
        $buttonId = 'aip-button-' . $productId;
        $productIsFree = $product->getFinalPrice() == 0;
        $methodCode = $productIsFree ? 'free' : $purchaseData['paymentToken']['method_code'];

        // JS component config
        $jsConfig = [
            'jsConfig' => array_merge(
                $this->customerHelper->getUserParams(),
                [
                    'product' => [
                        'id' => $this->getProduct()->getId(),
                    ],
                    'buttonSelector' => '#' . $buttonId
                ]
            )
        ];

?>
    <div id="aip-<?= $productId ?>" class="aip-button-container">
        <button 
            id="<?= $buttonId ?>"
            type="button"
            disabled="disabled"
            class="<?= $block->purchaseHelper->getButtonCss() ?> action primary instant-purchase aip-button"
            title="<?= __($config['general']['button_text']) ?>">
            <?= __($config['general']['button_text']) ?>
        </button>
    </div>

    <input type="hidden" name="aip[instant_purchase_payment_token][<?= $productId ?>]" value="<?= $purchaseData['paymentToken']['publicHash'] ?>" />
    <input type="hidden" name="aip[instant_purchase_method_code][<?= $productId ?>]" value="<?= $methodCode ?>" />
    <input type="hidden" name="aip[instant_purchase_shipping_address][<?= $productId ?>]" value="<?= $purchaseData['shippingAddress']['id'] ?>" />
    <input type="hidden" name="aip[instant_purchase_billing_address][<?= $productId ?>]" value="<?= $purchaseData['billingAddress']['id'] ?>" />
    <input type="hidden" name="aip[instant_purchase_carrier][<?= $productId ?>]" value="<?= $purchaseData['shippingMethod']['carrier'] ?>" />
    <input type="hidden" name="aip[instant_purchase_shipping][<?= $productId ?>]" value="<?= $purchaseData['shippingMethod']['method'] ?>" />

    <script type="text/x-magento-init">
        {
            "*": {
                "aip": <?= json_encode($jsConfig); ?>
            }
        }
    </script>
<?php } ?> 