<?php
    $config = $block->getConfig();
    if ($config && $block->purchaseHelper->canDisplayButton()) {
        //$purchaseData = $block->purchaseHelper->getPurchaseData();
?>
    <div id="aip-<?= $this->productHelper->getProduct()->getId() ?>" class="aip-button-container">
        <button 
            type="button"
            class="<?= $block->purchaseHelper->getButtonCss() ?> action primary instant-purchase aip-button"
            <?= $block->purchaseHelper->getButtonState() ?>
            title="<?= __($config['general']['button_text']) ?>">
            <?= __($config['general']['button_text']) ?>
        </button>
    </div>

    <script>
        require([
            'jquery',
            'Naxero_AdvancedInstantPurchase/js/view/instant-purchase',
            'domReady!'
        ], function ($, Aip) {
            'use strict';
                Aip.build();
        });
    </script>
<?php } ?>