<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
?>

<?php $msg = $block->getData('msg') ?>
<div class="messages">
    <div class="message error">
        <div class="message-text">
            <?= $block->escapeHtml($msg) ?>
        </div>
    </div>
</div>