<?php
    // Prepare the parameters
    $data = $block->getData('data');
    $title = $block->getData('title');
    $config = $block->getData('config');
    $productId = $config['product']['id'];
?>

<!-- UI logs viewer container -->
<div id="nbn-ui-logger-<?= $productId ?>" class="nbn-ui-logger">
    <h3><?= __('Product data') ?></h3>
    <pre class="nbn-logger-tree">
    </pre>

    <h3><?= __('Module parameters') ?></h3>
    <pre class="nbn-logger-tree">
    </pre>
</div>
