<?php $data = $block->getData('data') ?>
<?php $title = $block->getData('title') ?>
<?php $config = $block->getData('config') ?>

<div class="messages aip-ui-logger">
    <div class="message success">
        <?= $title ?>
        <div class="message-text">
            <pre class="aip-ui-logger-tree">
                <img src="<?= $config['ui']['loader'] ?>">
            </pre>
        </div>
    </div>
</div>
