<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */

$agreements = $block->getAgreements();
if (!$agreements) {
    return;
}

$agreementId = (int) $block->getRequest()->getParam('id');
?>
<ol id="nbn-checkout-agreements" class="agreements checkout items">
    <?php foreach ($agreements as $agreement): ?>
        <?php if ($agreement->getID() == $agreementId): ?>
            <li class="item">
                <div class="checkout-agreement-item-content nbn-agrement-link-content"<?= ($agreement->getContentHeight() ? ' style="height:' . $agreement->getContentHeight() . '"' : '') ?>>
                    <h2>
                        <?= $agreement->getIsHtml() ? $agreement->getCheckboxText() : $block->escapeHtml($agreement->getCheckboxText()) ?>
                    </h2>
                    <?php if ($agreement->getIsHtml()):?>
                        <?= /* @escapeNotVerified */ $agreement->getContent() ?>
                    <?php else:?>
                        <?= nl2br($block->escapeHtml($agreement->getContent())) ?>
                    <?php endif; ?>
                </div>
            </li>
        <?php endif; ?>
    <?php endforeach ?>
</ol>