<?php
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright © Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */

$agreements = $block->getAgreements();
if (!$agreements) {
    return;
}
?>
<ol id="checkout-agreements" class="agreements checkout items">
    <?php /** @var \Magento\CheckoutAgreements\Api\Data\AgreementInterface $agreement */ ?>
    <?php foreach ($agreements as $agreement): ?>
        <li class="item">
            <form id="checkout-agreements-form-<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>" class="field choice agree required">
                <?php if ($agreement->getMode() == \Magento\CheckoutAgreements\Model\AgreementModeOptions::MODE_MANUAL): ?>
                    <div class="nbn-agreement-link-row">
                        <input type="checkbox"
                            id="agreement-<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>"
                            name="agreement[<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>]"
                            value="1"
                            title="<?= $block->escapeHtml($agreement->getCheckboxText()) ?>"
                            class="checkbox nbn-agreement-box nbn-box"
                            data-validate="{required:true}"/>
                        <label class="label" for="agreement-<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>">
                            <a href="javascript:void(0)" class="nbn-agreement-link" data-role="Agreement" data-id="<?= $agreement->getId() ?>">
                                <span>
                                    <?= $agreement->getIsHtml() ? $agreement->getCheckboxText() : $block->escapeHtml($agreement->getCheckboxText()) ?>
                                </span>
                            </a>
                        </label>
                    </div>
                <?php elseif ($agreement->getMode() == \Magento\CheckoutAgreements\Model\AgreementModeOptions::MODE_AUTO): ?>
                <div id="checkout-agreements-form-<?= /* @escapeNotVerified */ $agreement->getAgreementId() ?>" class="field choice agree">
                    <span><?= $agreement->getIsHtml() ? $agreement->getCheckboxText() : $block->escapeHtml($agreement->getCheckboxText()) ?></span>
                </div>
                <?php endif; ?>
            </form>
        </li>
    <?php endforeach ?>
</ol>