<?php 
$agreements = $block->getAgreements();
if (!$agreements) {
    return;
}

$agreementId = (int) $block->getRequest()->getParam('id');
?>
<ol id="checkout-agreements" class="agreements checkout items">
    <?php /** @var \Magento\CheckoutAgreements\Api\Data\AgreementInterface $agreement */ ?>
    <?php foreach ($agreements as $agreement): ?>
        <?php if ($agreement->getID() == $agreementId): ?>
            <li class="item">
                <div class="checkout-agreement-item-content aip-agrement-link-content"<?= ($agreement->getContentHeight() ? ' style="height:' . $agreement->getContentHeight() . '"' : '') ?>>
                    <h2>
                        <?= $agreement->getIsHtml() ? $agreement->getCheckboxText() : $block->escapeHtml($agreement->getCheckboxText()) ?>
                    </h2>
                    <?php if ($agreement->getIsHtml()):?>
                        <?= /* @escapeNotVerified */ $agreement->getContent() ?>
                    <?php else:?>
                        <?= nl2br($block->escapeHtml($agreement->getContent())) ?>
                    <?php endif; ?>
                </div>
            </li>
        <?php endif; ?>
    <?php endforeach ?>
</ol>